import { Refine } from "@refinedev/core";
import { RefineKbar, RefineKbarProvider } from "@refinedev/kbar";
import routerProvider from "@refinedev/nextjs-router";
import { Metadata } from "next";
import React, { Suspense } from "react";
import { authProviderClient } from "@providers/auth-provider/auth-provider.client";
import { dataProvider, liveProvider } from "@providers/data-provider";
import "@styles/globals.css";

export const metadata: Metadata = {
  title: "Refine",
  description: "Generated by create refine app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    (<html lang="ja">
      <body>
        <Suspense>
          <RefineKbarProvider>
            <Refine
              routerProvider={routerProvider}
              authProvider={authProviderClient}
              dataProvider={dataProvider}
              liveProvider={liveProvider}
              options={{                
                syncWithLocation: true,
                warnWhenUnsavedChanges: true,
                useNewQueryKeys: true,
                projectId: "z4Qi4d-t7j7v8-dia0WO",
                liveMode: "auto",
              }}
              resources={[{
                name: "lessons",
                meta: {
                  label: "レッスン",
                },
                list: "/lessons",
                create: "/lessons/create",
                edit: "/lessons/edit/:id",
                show: "/lessons/show/:id"
              }, {
                name: "reservations",
                list: "/reservations",
                create: "/reservations/create",
                edit: "/reservations/edit/:id",
                show: "/reservations/show/:id"
              }, {
                name: "profiles",
                list: "/profiles",
                create: "/profiles/create",
                edit: "/profiles/edit/:id",
                show: "/profiles/show/:id"
              }, {
                name: "user-levels",
                list: "/user-levels",
                create: "/user-levels/create",
                edit: "/user-levels/edit/:id",
                show: "/user-levels/show/:id"
              }, {
                name: "lesson-levels",
                list: "/lesson-levels",
                create: "/lesson-levels/create",
                edit: "/lesson-levels/edit/:id",
                show: "/lesson-levels/show/:id"
              }, {
                name: "profiles",
                list: "/profiles",
                create: "/profiles/create",
                edit: "/profiles/edit/:id",
                show: "/profiles/show/:id"
              }, {
                name: "lesson_levels",
                list: "/lesson_levels",
                create: "/lesson_levels/create",
                edit: "/lesson_levels/edit/:id",
                show: "/lesson_levels/show/:id"
              }, {
                name: "lesson_schedules",
                list: "/lesson_schedules",
                create: "/lesson_schedules/create",
                edit: "/lesson_schedules/edit/:id",
                show: "/lesson_schedules/show/:id"
              }, {
                name: "user_levels",
                list: "/user_levels",
                create: "/user_levels/create",
                edit: "/user_levels/edit/:id",
                show: "/user_levels/show/:id"
              }]}>
              {children}
              <RefineKbar />
            </Refine>
          </RefineKbarProvider>
        </Suspense>
      </body>
    </html>)
  );
}
