name: Supabase Tests

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'supabase/**'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'supabase/**'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: supabase/package-lock.json

      - name: Install dependencies
        working-directory: ./supabase
        run: npm ci
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Start Supabase
        run: |
          supabase init --force
          supabase start
          # データベースが起動するまで待機（最大60秒）
          for i in {1..12}; do
            if supabase status | grep -q "Database online"; then
              echo "Database is online"
              break
            fi
            echo "Waiting for database to come online... (attempt $i/12)"
            sleep 5
          done
          # データベースのリセットと初期化
          supabase db reset
          # マイグレーション完了を待機（追加で30秒）
          sleep 30

      - name: Run tests
        working-directory: ./supabase
        run: npm test
        env:
          SUPABASE_URL: http://localhost:54321
          SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
          SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU

      - name: Stop Supabase
        if: always()
        run: supabase stop 